# VARIABLES
@fullhost = http://localhost:8080

# REQUESTS
## PAGES
### BUTTONS
GET {{fullhost}}/layout?name=buttons HTTP/1.1
### MULTIPAGES
GET {{fullhost}}/layout?name=multipage HTTP/1.1
### CHILD PARENT
GET {{fullhost}}/layout?name=children-parent HTTP/1.1
### BIG
GET {{fullhost}}/layout?name=big HTTP/1.1
### COMPONENTS
GET {{fullhost}}/layout?name=comp HTTP/1.1
### ERROR RECOVER
GET {{fullhost}}/layout?name=error-recover HTTP/1.1

### TEST HTML
PATCH {{fullhost}}/layout/test HTTP/1.1
Content-Type: application/x-www-form-urlencoded

html={{ $a := get "/a" . | string }}{{ $b := get "/b" . | array }}<h1>{{ $a }}</h1>{{ range array $b }}<span>{{ . }}</span>{{ end }}{{ $c := get "/c/c1" . | float | currency "pt-BR" }}<p>{{ $c }}</p><span>{{ get "/d" . | integer }}</span>
&data={ "a": "A", "b": [ "b1", "b2" ], "c": {"c1": 45.0}, "d": 1}