FROM golang
WORKDIR /app
COPY ./src ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/uihtml
ARG REDIS_ADDR
ENV REDIS_ADDR=$REDIS_ADDR
ARG REDIS_PASS
ENV REDIS_PASS=$REDIS_PASS
ARG AWS_CRED_NAME
ENV AWS_CRED_NAME=$AWS_CRED_NAME
ARG AWS_CRED_SECRET
ENV AWS_CRED_SECRET=$AWS_CRED_SECRET
ARG AWS_ENDPOINT
ENV AWS_ENDPOINT=$AWS_ENDPOINT
ARG AWS_REGION
ENV AWS_REGION=$AWS_REGION
CMD [ "/bin/uihtml" ]