version: '3'

services:
  r:
    image: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASS: ${REDIS_PASS}
    command: redis-server --save 60 1 --requirepass ${REDIS_PASS}