version: '3'

services:
  r:
    image: redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .redisenv
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASS:? REDIS_PASS not set}"
    networks:
      - net
networks:
  net:
    driver: bridge